### ISSUE TITLE
Default setting neither shows widgets icons nor terrain nor buildings

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Viz-Template#35]
With [commit bfb18d081141f1a](https://github.com/VCityTeam/UD-Viz-Template/tree/bfb18d081141f1a8d79d218211f4e3c71845b61d) (Firefox 89.0.2, OSX 10.14.6)  UD-Viz display (prior to any interactions) looks like the following picture, that is it misses widgets on left side-bar, some terrain as well as e.g. some 3dTiles tileset 
<img width="1241" alt="Screen Shot 2021-09-14 at 1 28 10 PM" src="https://user-images.githubusercontent.com/26405741/133249877-3a0bbd45-9048-4189-8357-c960efa169db.png">

**Comment by valentinMachado** [comment]
I am goind to remove useless entry in the config.json and add module with javascript inside the bootstrap.js, this should fix this
