### ISSUE TITLE
Switch to using UD-Viz's view3D class

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Viz-Template#37]
Have the main app (in bootstrap.js) use [src/Views/View3D](https://github.com/VCityTeam/UD-Viz/blob/master/src/Views/View3D/View3D.js) instead of bypass/direct calls to [ `addBaseMapLayer()`, `addElevationLayer()` and `setupAndAdd3DTilesLayers()`](https://github.com/VCityTeam/UD-Viz-Template/blob/master/src/bootstrap.js#L8).

Additionnaly move the [config.json documentation of the iTowns layer](https://github.com/VCityTeam/UD-Viz/blob/dev-unstable/Doc/Devel/LocalGameTutorial.md#parameterize-itowns-layers) to UD-Viz/View3D documentation.

**Comment by clementcolin** [comment]
This would now be solved by upgrading the ud-viz version and make the necessary induced changes

**Comment by clementcolin** [comment]
Done with last [ud-viz update 2.38](https://github.com/VCityTeam/UD-Viz-Template/commit/b9c1e8663e43e21bb7b6814b0b2d08815b2b2c48)
