### ISSUE TITLE
Impossible to install on Windows

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz-Template#40]
After cloning the repository, and doing `npm install`, I get the following message :

`npm WARN html-loader@2.1.2 requires a peer of webpack@^5.0.0 but none is installed. You must install peer dependencies yourself.` and so on.

I tried to update in the package.json the version of webpack, but `npm install` kept showing new errors.

How do we fix that ? 

[Proposed PR](https://github.com/VCityTeam/UD-Viz-Template/pull/43).

**Comment by valentinMachado** [comment]
related to this issue https://github.com/VCityTeam/UD-Viz-Template/issues/41

**Comment by EricBoix** [comment]
@clementcolin Could you please confirm that you encounter this issue when on npm version 7.X ?

**Comment by EricBoix** [comment]
I encountered a very similar issue with npm verion 7.24.2 (on OSX). The ERROR message goes
```bash
npm ERR! While resolving: app_name@1.0.0
npm ERR! Found: webpack@4.46.0
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^4.46.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^5.0.0" from html-loader@2.1.2
npm ERR! node_modules/html-loader
npm ERR!   dev html-loader@"^2.1.2" from the root project
```

**Comment by EricBoix** [comment]
UD-Viz is known for working with npm version 7.X. UD-Viz-Template shoudl be update/enhanced to also support version 7.X.

**Comment by EricBoix** [comment]
[Proposed PR](https://github.com/VCityTeam/UD-Viz-Template/pull/43).
