### ISSUE TITLE
Update webpack version from 4.46.0 to 5.0.0

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Viz-Template#41]

**Comment by valentinMachado** [comment]
the 4.46.0 version of webpack conflict with the installation on the html-loader package which require the 5.0.0 version

**Comment by agrignard** [comment]
While working on tis issue https://github.com/VCityTeam/UD_ReAgent_ABM/issues/7 I am trying to set my own UD_Viz_Tempalte however I confirm I also have this issue trying to run UD_VIZ_Template 


`````
arno@wu-pers-01396 UD-Viz-Template % npm install         
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: app_name@1.0.0
npm ERR! Found: webpack@4.46.0
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^4.46.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^5.0.0" from html-loader@2.1.2
npm ERR! node_modules/html-loader
npm ERR!   dev html-loader@"^2.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
`````


Do we know if this can easily be fixed?

**Comment by DiegoVinasco** [comment]
It appears this conflict is related npm's version. 

With node version `v14.18.0` and npm version `6.14.15` this error does not appear (at least in my environment nor within the last travis build).
After testing with npm version `7.5.0` I can recreate this error.

For the time being if you need to run a quick demo, you can change your npm version with this command:
```
npm install -g npm@6.14.10
```
